document.write("<footer>");
document.write("    <center>");
document.write("    <!--Socials-->");
document.write("    <div class=\"footer-content\">");
document.write("    <h3>Team 815<\/h3>      ");
document.write("    <p><a href=\"Team815.html\"><img src=\"Images\/Logo.png\" width=\"100\" height=\"100\"><\/a>");
document.write("  ");
document.write("    <p>This is a footer, we have one because all good websites do.<\/p>");
document.write("    <ul class=\"footer-socials\">");
document.write("    <li><a href=\"https:\/\/www.instagram.com\/frc.815\/\"><img src=\"Images\/Insta.png\" height=\"50\" width=\"50\"><i class=\"https:\/\/www.instagram.com\/frc.815\/\"><\/i><\/a><\/li>");
document.write("    <li><a href=\"https:\/\/www.youtube.com\/user\/FRC815\/featured\"><img src=\"Images\/Youtube.png\" height=\"70\" width=\"70\"><i class=\"https:\/\/www.instagram.com\/frc.815\/\"><\/i><\/a><\/li>");
document.write("    <li><a href=\"https:\/\/www.instagram.com\/frc.815\/\"><img src=\"Images\/Facebook.png\" height=\"50\" width=\"50\"><i class=\"https:\/\/www.instagram.com\/frc.815\/\"><\/i><\/a><\/li>");
document.write("    <\/ul>");
document.write("    <\/div>");
document.write("    <!--Directs-->");
document.write("    <div class=\"footer-bottom\">");
document.write("    <a href=\"Sub\/Changelogs.html\">");
document.write("    <p><span class=\"Ver\"><\/span><\/p><\/a>");
document.write("    <div class=\"footer-menu\">");
document.write("    <ul class=\"f-menu\">");
document.write("    <li><a href=\"Team815.html\">Home<\/a><\/li>");
document.write("    <li><a href=\"Sub\/About.html\">About Us<\/a><\/li>");
document.write("    <li><a href=\"Sub\/Robot.html\">Our Robots<\/a><\/li>");
document.write("    <li><a href=\"Sub\/Fundraiser.html\">Fundraising<\/a><\/li>");
document.write("    <li><a href=\"Sub\/Sponsors.html\">Sponsors<\/a><\/li>");
document.write("    <\/ul>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("    <\/center>");
document.write("<\/footer>");
